//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class ext_button {

		[JsonProperty]
		public string btn_href { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string btn_name { get; set; } = string.Empty;

		[JsonProperty, Column(IsIdentity = true)]
		public int id { get; set; }

		[JsonProperty, Column(DbType = "char(24)")]
		public string pid { get; set; } = string.Empty;

	}

}
