//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class pay_history {

		/// <summary>
		/// 咨询问题Id
		/// </summary>
		[JsonProperty, Column(DbType = "char(24)")]
		public string device_info { get; set; } = string.Empty;
		/// <summary>
		/// 专家openId
		/// </summary>
		[JsonProperty, Column(DbType = "char(28)")]
		public string expert_id { get; set; } = string.Empty;
		/// <summary>
		/// 专家数据Id
		/// </summary>
		public string expert_did { get; set; } = "000000000000000000000000";
		/// <summary>
		/// 专家名称
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string expert_name { get; set; } = string.Empty;
		/// <summary>
		/// 打赏者openId
		/// </summary>
		[JsonProperty, Column(DbType = "char(28)")]
		public string openid { get; set; } = string.Empty;
		/// <summary>
		/// 订单号
		/// </summary>
		[JsonProperty, Column(DbType = "char(24)")]
		public string out_trade_no { get; set; } = string.Empty;

		/// <summary>
		/// 打赏时间
		/// </summary>
		[JsonProperty, Column(DbType = "datetime")]
		public DateTime pay_time { get; set; }

		/// <summary>
		/// 时间戳
		/// </summary>
		[JsonProperty]
		public long time_end { get; set; }
		/// <summary>
		/// 费用
		/// </summary>
		[JsonProperty]
		public int total_fee { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string transaction_id { get; set; } = string.Empty;

	}

}
