//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models
{

	[JsonObject(MemberSerialization.OptIn)]
	public partial class sys_dept
	{
		/// <summary>
		/// 部门id
		/// </summary>
		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public long id { get; set; }

		/// <summary>
		/// 祖级列表
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string ancestors { get; set; } = string.Empty;

		/// <summary>
		/// 创建者
		/// </summary>
		[JsonProperty, Column(StringLength = 64)]
		public string create_by { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(DbType = "datetime")]
		public DateTime create_time { get; set; }

		/// <summary>
		/// 删除标志（0代表存在 2代表删除）
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int del_flag { get; set; }

		/// <summary>
		/// 部门名称
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string dept_name { get; set; } = string.Empty;

		/// <summary>
		/// 部门状态（0正常 1停用）
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int dept_status { get; set; }

		/// <summary>
		/// 部门类型（0公司，1部门）
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int dept_type { get; set; }

		/// <summary>
		/// 邮箱
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string email { get; set; } = string.Empty;

		/// <summary>
		/// 负责人
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string leader { get; set; } = string.Empty;

		/// <summary>
		/// 负责人ID
		/// </summary>
		[JsonProperty]
		public long leader_id { get; set; }

		/// <summary>
		/// 显示顺序
		/// </summary>
		[JsonProperty, Column(DbType = "int(4)")]
		public int order_num { get; set; }

		/// <summary>
		/// 父部门id
		/// </summary>
		[JsonProperty]
		public long parent_id { get; set; }

		/// <summary>
		/// 联系电话
		/// </summary>
		[JsonProperty, Column(StringLength = 11)]
		public string phone { get; set; } = string.Empty;

		/// <summary>
		/// 更新者
		/// </summary>
		[JsonProperty, Column(StringLength = 64)]
		public string update_by { get; set; } = string.Empty;

		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(DbType = "datetime")]
		public DateTime update_time { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(StringLength = 255)]
		public string remark { get; set; }
	}

}
