//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class sys_user {

		/// <summary>
		/// 用户id
		/// </summary>
		[JsonProperty, Column(IsPrimary = true)]
		public long id { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string create_by { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty]
		public DateTime create_time { get; set; }

		/// <summary>
		/// 删除标志（0代表存在 1代表删除）
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int del_flag { get; set; }

		/// <summary>
		/// 部门
		/// </summary>
		[JsonProperty]
		public int dept_id { get; set; }

		/// <summary>
		/// 部门
		/// </summary>
		[JsonProperty]
		public string dept_name { get; set; } = string.Empty;

		/// <summary>
		/// 邮箱
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string email { get; set; } = string.Empty;

		/// <summary>
		/// 用户性别（1男 0女 2未知）
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int gender { get; set; }

		/// <summary>
		/// 是否是超管(0-不是，1-是)
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int is_super { get; set; }

		/// <summary>
		/// 登录账号
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string login_name { get; set; } = string.Empty;

		/// <summary>
		/// 手机号码
		/// </summary>
		[JsonProperty, Column(StringLength = 20)]
		public string mobile_phone { get; set; } = string.Empty;

		/// <summary>
		/// 密码
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string pass_word { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty]
		public string remark { get; set; } = string.Empty;

		/// <summary>
		/// 角色id
		/// </summary>
		[JsonProperty]
		public long role_id { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string update_by { get; set; } = string.Empty;

		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(DbType = "datetime")]
		public DateTime update_time { get; set; }

		/// <summary>
		/// 用户头像
		/// </summary>
		[JsonProperty]
		public string user_avatar { get; set; } = string.Empty;

		/// <summary>
		/// 用户名
		/// </summary>
		[JsonProperty, Column(StringLength = 30)]
		public string user_name { get; set; } = string.Empty;

		/// <summary>
		/// 账号状态(0-正常，1-禁用)
		/// </summary>
		[JsonProperty, Column(DbType = "int(1)")]
		public int user_status { get; set; }


		/// <summary>
		/// 角色名称
		/// </summary>
		[JsonProperty, Column(IsIgnore = true)]
		public string role_name { get; set; }
		/// <summary>
		/// 职位信息
		/// </summary>
		[JsonProperty, Column(IsIgnore =true)]
		public List<long> positionList { get; set; }

	}

}
