//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class sys_operate {

		[JsonProperty, Column(IsPrimary = true)]
		public long id { get; set; }

		/// <summary>
		/// 排序
		/// </summary>
		[JsonProperty, Column(DbType = "int(5)")]
		public int func_sort { get; set; }

		/// <summary>
		/// 按钮名称
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string func_title { get; set; } = string.Empty;

		/// <summary>
		/// 菜单Id
		/// </summary>
		[JsonProperty]
		public long menu_id { get; set; }

		/// <summary>
		/// 权限标识
		/// </summary>
		[JsonProperty, Column(StringLength = 50)]
		public string role_tag { get; set; } = string.Empty;


	}

}
