//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class sys_citys {

		[JsonProperty, Column(DbType = "int(12)")]
		public int city_code { get; set; }

		[JsonProperty, Column(DbType = "int(2)")]
		public int city_level { get; set; }

		[JsonProperty, Column(DbType = "bigint(255)")]
		public long id { get; set; }

		[JsonProperty, Column(DbType = "varchar(100)")]
		public string name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "int(12)")]
		public int province_code { get; set; }

		[JsonProperty, Column(DbType = "int(12)")]
		public int zipcode { get; set; }

	}

}
