# Logging
Logging:
  LogLevel:
    Default: "Debug"
    System: "Information"
    Microsoft: "Information"
#开始ServerGC模式
configProperties:
   System.GC.Server: true
   System.GC.Concurrent: true
#运行环境 0-开发，1-发布
RuntimeEnvironment: 1
# 站点host http://*:80;
HostUrl: "http://cmsl.atlass:80"
#跨域
AllowedHosts: "*"
#freesql的配置
FreeSqlConfig:  
  LogSql: true  #是否记录sql,true记录，false不记录
#数据库配置
DbConfigs: 
  -
   Enable: true
   DataType: 0 #mysql
   MasterConnection: "Data Source=127.0.0.1;Port=3306;Initial Catalog=easycms_net5;user id=root;password=123123;Max Pool Size=10;Connection Timeout=5;CharSet=utf8mb4;"
   SlaveConnections: []
  -
   Enable: false
   DataType: 1 #SqlServer
   MasterConnection: "Data Source=.;Initial Catalog=RealidSystem;User ID=sa;Password=123;Max Pool Size=10;Connection Timeout=5;"
   SlaveConnections: []
  -
   Enable: false
   DataType: 2 #PostgreSQL
   MasterConnection: "Server=localhost;Port=5433;Username=postgres;Password=123456;Database=easy_cms;Max Pool Size=10;Connection Timeout=5;"
   SlaveConnections: []
  -
   Enable: false
   DataType: 3 #Oracle
   MasterConnection: ""
   SlaveConnections: []
  -
   Enable: false
   DataType: 4 #Sqlite
   MasterConnection: ""
   SlaveConnections: []
#Redis配置
RedisConfig: 
  Enable: true
  Host: "127.0.0.1:6379"
  User: "" #redis6.0需要
  Password: ""
  Db: 0
  MaxPoolSize: 200 
  MinPoolSize: 10
  ConnectTimeout: 5000
  ConnectionName: "easycms"
  PreKey: "{easycms}:"
#定时任务配置
Crontab: 
  Enable: true #是否开启hanfire  如果部署到IIS注意配置应用程序池的“禁用重叠回收为true”否则会造成资源占用问题
  CheckInterval: 10 #健康检查的时间间隔
  Storage:  0   #0-Sqlite,1-LiteDb
 #CO2NET 设置
SenparcSetting: 
  IsDebug: true
  DefaultCacheNamespace: "EasyCMSCache"
  Cache_Redis_Configuration: "#{Cache_Redis_Configuration}#" #Redis配置
  # Cache_Redis_Configuration: "localhost:6379" #不包含密码
  # Cache_Redis_Configuration": "localhost:6379,password=senparc,connectTimeout=1000,connectRetry=2,syncTimeout=10000,defaultDatabase=3",//密码及其他配置
  Cache_Memcached_Configuration: "#{Cache_Memcached_Configuration}#" #Memcached配置
  SenparcUnionAgentKey: "#{SenparcUnionAgentKey}#" #SenparcUnionAgentKey
#Senparc.Weixin SDK 设置
SenparcWeixinSetting:
  IsDebug: true
  Token: "easycms"
  EncodingAESKey: "IV6OT1ZdgVmW0ApgEhtg6KMgM1N9co7NFT2yJ9QtROL"
  WeixinAppId: "wxb41a3968afc0e96b"
  WeixinAppSecret: "5382de09bdf77a259aa2036bac417b90"
  #微信支付
  #微信支付V3（新版）
  TenPayV3_MchId: "1487074472"
  TenPayV3_SubMchId: "" #子商户，没有可留空
  TenPayV3_Key: "B99MGW5XK4YC22G5X3S8G2TR6P8RW31Q"
  TenPayV3_AppId: "wxb41a3968afc0e96b"
  TenPayV3_AppSecret: "5382de09bdf77a259aa2036bac417b90"
  TenPayV3_TenpayNotify: "http://www.yushuo.natapp1.cc/wxpay/Index"
  #如果不设置TenPayV3_WxOpenTenpayNotify，默认在 TenPayV3_TenpayNotify 的值最后加上 "WxOpen"
  TenPayV3_WxOpenTenpayNotify: "http://www.yushuo.natapp1.cc/wxpay/Index" #http://YourDomainName/TenpayV3/PayNotifyUrlWxOpen
#媒体类型
Mime: 
  ".properties": "application/x-javascript"
  ".bak": "application/octet-stream"
#Extension: ".apk"
#MimeType: "application/vnd.android.package-archive"
#  -
#   Extension: ".bak"
#   MimeType: "application/octet-stream"
