//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models
{

	//[JsonObject(MemberSerialization.OptIn)]
	public partial class cms_content
	{
		[JsonProperty,Column(IsPrimary =true,IsIdentity =true)]
		public int id { get; set; }
		/// <summary>
		/// 文字标题
		/// </summary>
		[JsonProperty]
		public string title { get; set; } = string.Empty;
		/// <summary>
		/// 副标题
		/// </summary>
		[JsonProperty]
		public string sub_title { get; set; } = string.Empty;

		/// <summary>
		/// 文字内容
		/// </summary>
		[JsonProperty, Column(DbType = "longtext")]
		public string content { get; set; } = string.Empty;

		/// <summary>
		/// 简介
		/// </summary>
		[JsonProperty, Column(DbType = "text")]
		public string summary { get; set; } = string.Empty;
		/// <summary>
		/// 封面图片
		/// </summary>
		[JsonProperty]
		public string cover_image { get; set; } = string.Empty;
		/// <summary>
		/// 作者
		/// </summary>
		[JsonProperty]
		public string author { get; set; } = string.Empty;

		/// <summary>
		/// 文章来源
		/// </summary>
		[JsonProperty]
		public string source { get; set; } = string.Empty;
		/// <summary>
		/// 栏目
		/// </summary>
		[JsonProperty]
		public int channel_id { get; set; }

		/// <summary>
		/// 部门
		/// </summary>
		[JsonProperty]
		public int dept_id { get; set; }
		/// <summary>
		/// 是否限制ip访问
		/// </summary>
		[JsonProperty, Column(DbType = "tinyint(1)")]
		public int ip_limit { get; set; }

		/// <summary>
		/// 审核状态 0-待审，1-通过，2-草稿，100-审核不通过
		/// </summary>
		[JsonProperty, Column(DbType = "tinyint(2)")]
		public int status { get; set; }
        /// <summary>
		/// 置顶
		/// </summary>
		public int is_top { get; set; }
		/// <summary>
		/// 标签
		/// </summary>
		[JsonProperty]
		public string tags { get; set; } = string.Empty;

		/// <summary>
		/// 外部链接
		/// </summary>
		[JsonProperty]
		 public string content_href { get; set; }

		/// <summary>
		/// 点击量 用来统计是否热门，比如超过100自动为热门
		/// </summary>
		[JsonProperty]
		public int hit_count { get; set; }
		/// <summary>
		/// 设置推荐
		/// </summary>
		[JsonProperty]
		public int is_recommend { get; set; }
		[JsonProperty]
		public long insert_id { get; set; }

		[JsonProperty, Column(DbType = "datetime")]
		public DateTime insert_time { get; set; }
		[JsonProperty]
		public long update_id { get; set; }

		[JsonProperty, Column(DbType = "datetime")]
		public DateTime update_time { get; set; }

	}

}

