//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class question_imgs {

		[JsonProperty, Column(IsIdentity = true)]
		public int id { get; set; }
		/// <summary>
		/// 0-提问图片,1-回复图片
		/// </summary>
		[JsonProperty, Column(DbType = "tinyint(2)")]
		public int img_type { get; set; }

		[JsonProperty]
		public string img_url { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "char(24)")]
		public string pid { get; set; } = string.Empty;

		/// <summary>
		/// 第几次回复上传的图片
		/// </summary>
		[JsonProperty, Column(DbType = "tinyint(2)")]
		public int up_number { get; set; }

	}

}
