//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Atlass.Framework.Models {

	
	public partial class quick_reply {

		[JsonProperty, Column(IsPrimary = true)]
		public string id { get; set; }

		/// <summary>
		/// 专家openid
		/// </summary>
		[JsonProperty, Column(DbType = "char(28)")]
		public string insert_id { get; set; } = string.Empty;
		/// <summary>
		/// 专家id
		/// </summary>
		public string expert_id { get; set; }

		[JsonProperty, Column(DbType = "datetime")]
		public DateTime insert_time { get; set; }

		/// <summary>
		/// 备注标题
		/// </summary>
		public string qtitle { get; set; }
		[JsonProperty]
		public string qcontent { get; set; } = string.Empty;

		/// <summary>
		/// 0-快捷回复，1-私人资料
		/// </summary>
		public int qtype { get; set; }

		/// <summary>
		/// 专家名称
		/// </summary>
		[Column(IsIgnore =true)]
		public string expertName { get; set; }
	}

}
